global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

scrape_configs:
  - job_name: prometheus
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - localhost:9090
          
  - job_name: prometheus-scraper 
    static_configs:
      - targets:
          - localhost:9100 # IP Address of the Prometheus Server

  - job_name: 'postgres_exporter'
    static_configs:
      - targets:
          - localhost:9187  # Monitor PostgreSQL metrics

  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets:
        - cadvisor:8080        

